;;; t15.lisp — Embedded points, lines and surfaces

;; By default, across geometrical dimensions meshes generated by Gmsh are only
;; conformal if lower dimensional entities are on the boundary of higher
;; dimensional ones (i.e. if points, curves or surfaces are part of the boundary
;; of volumes).

;; Embedding constraints allow to force a mesh to be conformal to other lower
;; dimensional entities.

;; Copied from t1.lisp...
(let ((lc 1e-2))
  (geo:point 0 0 0 :mesh-size lc :tag 1)
  (geo:point 0.1 0 0 :mesh-size lc :tag 2)
  (geo:point 0.1 0.3 0 :mesh-size lc :tag 3)
  (geo:point 0 0.3 0 :mesh-size lc :tag 4)
  (geo:line 1 2 :tag 1)
  (geo:line 3 2 :tag 2)
  (geo:line 3 4 :tag 3)
  (geo:line 4 1 :tag 4)
  (geo:curve-loop '(4 1 -2 3) :tag 1)
  (geo:plane-surface '(1) :tag 1)

  ;; We change the mesh size to generate a coarser mesh
  (let ((lc (* lc 4)))
    (geo:mesh-set-size '((0 . 1) (0 . 2) (0 . 3) (0 . 4)) lc)

    ;; We define a new point
    (geo:point 0.02 0.02 0.0 :mesh-size lc :tag 5)

    ;; We have to synchronize before embedding entities:
    (geo:synchronize)

    ;; One can force this point to be included ("embedded") in the 2D mesh,
    ;; using the embed() function:
    (mesh:embed 0 '(5) 2 1)

    ;; In the same way, one can use embed() to force a curve to be embedded in
    ;; the 2D mesh:
    (geo:point 0.02 0.12 0.0 :mesh-size lc :tag 6)
    (geo:point 0.04 0.18 0.0 :mesh-size lc :tag 7)
    (geo:line 6 7 :tag 5)

    (geo:synchronize)
    (mesh:embed 1 '(5) 2 1)

    ;; Points and curves can also be embedded in volumes
    (geo:extrude '((2 . 1)) 0 0 0.1)

    (let ((p (geo:point 0.07 0.15 0.025 :mesh-size lc)))

      (geo:synchronize)
      (mesh:embed 0 (list p) 3 1)

      (geo:point 0.025 0.15 0.025 :mesh-size lc :tag (1+ p))
      (let ((l (geo:line 7 (1+ p))))

        (geo:synchronize)
        (mesh:embed 1 (list l) 3 1)

        ;; Finally, we can also embed a surface in a volume:
        (geo:point 0.02 0.12 0.05 :mesh-size lc :tag (+ p 2))
        (geo:point 0.04 0.12 0.05 :mesh-size lc :tag (+ p 3))
        (geo:point 0.04 0.18 0.05 :mesh-size lc :tag (+ p 4))
        (geo:point 0.02 0.18 0.05 :mesh-size lc :tag (+ p 5))

        (geo:line (+ p 2) (+ p 3) :tag (+ l 1))
        (geo:line (+ p 3) (+ p 4) :tag (+ l 2))
        (geo:line (+ p 4) (+ p 5) :tag (+ l 3))
        (geo:line (+ p 5) (+ p 2) :tag (+ l 4))

        (let* ((ll (geo:curve-loop (list (+ l 1) (+ l 2) (+ l 3) (+ l 4))))
               (s (geo:plane-surface (list ll))))

          (geo:synchronize)
          (mesh:embed 2 (list s) 3 1))))))

;; Note that with the OpenCASCADE kernel (see t16.lisp), when the fragment()
;; function is applied to entities of different dimensions, the lower
;; dimensional entities will be automatically embedded in the higher dimensional
;; entities if necessary.

(mesh:generate :dim 3)
;; (gmsh:write "/tmp/t15.msh")
